apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mongodb-stateful-build
objects:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: "mongodb"
    labels:
      app: mongodb
  spec:
    serviceName: "mongodb-internal"
    selector:
      matchLabels:
        name: mongodb
    replicas: 3
    template:
      metadata:
        labels:
          name: mongodb
      spec:
        containers:
          - name: mongodb-container
            image: "registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest"
            ports:
              - containerPort: 27017
                name: mongodb-port
            args:
              - "run-mongod-replication"
            volumeMounts:
              - name: mongodb-data
                mountPath: "/var/lib/mongodb/data"
            env:
              - name: MONGODB_DATABASE
                value: "${MONGODB_DATABASE}"
              - name: MONGODB_USER
                value: "${MONGODB_USER}"
              - name: MONGODB_PASSWORD
                value: "${MONGODB_PASSWORD}"
              - name: MONGODB_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secrets
                    key: mongodb-admin-password 
              - name: MONGODB_REPLICA_NAME
                value: "rs0"
              - name: MONGODB_KEYFILE_VALUE
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secrets
                    key: mongodb-keyfile-value
              - name: MONGODB_SERVICE_NAME
                value: "${MONGODB_SERVICE}"
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: mongodb-data
          labels:
            name: "mongodb"
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: "4Gi"
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongodb
  spec:
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Secret
  metadata:
    name: mongodb-secrets
  stringData:
    mongodb-admin-password: "${MONGODB_ADMIN_PASSWORD}"
    mongodb-keyfile-value: "${MONGODB_KEYFILE_VALUE}"
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongodb-internal
  spec:
    clusterIP: None
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: Random MongoDB admin password.
  displayName: Mongo DB Admin Password
  name: MONGODB_ADMIN_PASSWORD
  required: true
  from: "[a-zA-Z0-9]{16}"
  generate: expression
- description: MongoDB KeyFile Value.
  displayName: MongoDB KeyFile Value
  name: MONGODB_KEYFILE_VALUE
  required: true
  from: "[a-zA-Z0-9]{16}"
  generate: expression
- description: MongoDB Database Name.
  displayName: MongoDB Database
  name: MONGODB_DATABASE
  required: true
  value: parks
- description: MongoDB User Name.
  displayName: MongoDB User
  name: MONGODB_USER
  required: true
  value: mongodb
- description: MongoDB User Password.
  displayName: MongoDB Password
  name: MONGODB_PASSWORD
  required: true
  value: mongodb
- description: MongoDB Service Name.
  displayName: MongoDB Service
  name: MONGODB_SERVICE
  required: true
  value: mongodb-internal

