apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: parksmap-pipeline-build
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: parksmap-pipeline
    name: parksmap-pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: "https://github.com/paulgreenbank/openshift-app-development"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GUID
          value: "GUID_VARIABLE"
        - name: CLUSTER
          value: "CLUSTER_VARIABLE"
        jenkinsfilePath: ParksMap/Jenkinsfile
      type: JenkinsPipeline
